trigger:
- '*'

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello from Azure DevOps!
  displayName: 'Run a script'

- script: echo Deploy your application here
  displayName: 'Deploy'
